### ISSUE TITLE
Does it work with ADK?

### ISSUE THREAD

**Issue by ghost** [felis/UHS30#14]
Hi,
I would like to try this out!  I am currently using the USB Host 2.0 library with Android ADK and am finding issues with the Usb.Task().  I think an interrupt based usb host would work better.

Is there a UHS3.0 example that would work with ArduinoBlinkLED for Android, like there is for the UHS2.0?  If not, any other examples that work with ADK?

Thanks!

**Comment by xxxajk** [comment]
Should work, try it.

**Comment by ghost** [comment]
Ok.

Quick first question.  What is the replacement of adk.RcvData and adk.SndData in the UHS3 library?

**Comment by xxxajk** [comment]
If you are expecting the accessory mode to work, the interface driver for it is not yet written. 
You are welcome to help out, though.
What should work:  https://github.com/felis/UHS30#current-working-interface-drivers

**Comment by xxxajk** [comment]
BTW, Don't cut yourself short on skills. 
**# ANY** kind of help is appreciated.

**Comment by xxxajk** [comment]
Now In progress with help.

**Comment by xxxajk** [comment]
ADK is now working.
Please let me know if it works for you.

**Comment by shadeyinka** [comment]
UHS20 works with Arduino Mega ADK but UHS30 seem not to work.UHS_FS/UHS_HOST_SHIELD/UHS_FS_NEW_DEMO
Compiles OK But
Execution gets stuck at while(KINETIS_Usb.Init(1000) != 0);

**Comment by xxxajk** [comment]
Arduino Mega ADK now supported...
